# Generated by Django 5.0 on 2024-02-03 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0002_alter_question_choice_trigger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="parent_question",
            new_name="parent",
        ),
    ]
