# Generated by Django 5.0 on 2024-02-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0004_alter_choice_number_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question",
                to="poll.test",
            ),
        ),
    ]
