# Generated by Django 5.0 on 2024-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0006_alter_choice_question_alter_question_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="display",
            field=models.CharField(
                choices=[("True", "True"), ("False", "False")],
                default=None,
                max_length=20,
                verbose_name="Видимость вопроса",
            ),
        ),
    ]
