# Generated by Django 5.0 on 2024-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0007_question_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="display",
            field=models.CharField(
                choices=[(True, True), (False, False)],
                default=None,
                max_length=20,
                verbose_name="Видимость вопроса",
            ),
        ),
    ]
