# Generated by Django 5.0 on 2024-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0008_alter_question_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="display",
            field=models.CharField(
                blank=True,
                choices=[(True, True), (False, False)],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Видимость вопроса",
            ),
        ),
    ]
