# Generated by Django 5.0 on 2024-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0009_alter_question_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="display",
            field=models.BooleanField(default=True, verbose_name="Видимость вопроса"),
        ),
    ]
